services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token eyJhIjoiNmRlZDQ5YWYyMDAyYmI3OThhNDRmMjg3MzJhNmQyMjUiLCJ0IjoiYzc1ZTFhYWYtNzhkMS00MGYxLTkzNWMtODNmZDE5MGU3NzQ0IiwicyI6Ik5ESmhaR1UyWm1RdE1UbGlaQzAwTkdJMkxXRXdNMk10TmpKa01EbGhZekF4T0dFMyJ9
    restart: unless-stopped