services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token eyJhIjoiNmRlZDQ5YWYyMDAyYmI3OThhNDRmMjg3MzJhNmQyMjUiLCJ0IjoiYzc1ZTFhYWYtNzhkMS00MGYxLTkzNWMtODNmZDE5MGU3NzQ0IiwicyI6IlkySmxOV0V3TW1NdFlUUTRZaTAwWkRBd0xXSTFZVE10TURrMk5qUm1NbVJtWVdReSJ9
    restart: unless-stopped